const foods=[{id:1,name:"Pepperoni Pizza",category:"Pizza",restaurant:"Pizza House",price:28000,eta:30,emoji:"🍕"},{id:2,name:"Chicken & Chips",category:"Chips",restaurant:"Kampala Grill",price:12000,eta:25,emoji:"🍗"},{id:3,name:"Rolex Chapati",category:"Chapati",restaurant:"Street Bites",price:7000,eta:15,emoji:"🌯"},{id:4,name:"Loaded Burger",category:"Burgers",restaurant:"Urban Bites",price:18000,eta:20,emoji:"🍔"},{id:5,name:"Crispy Chicken",category:"Chicken",restaurant:"Kampala Grill",price:15000,eta:22,emoji:"🍗"},{id:6,name:"Chips Masala",category:"Chips",restaurant:"Street Bites",price:9000,eta:18,emoji:"🍟"},{id:7,name:"Chicken Pizza",category:"Pizza",restaurant:"Pizza House",price:26000,eta:28,emoji:"🍕"},{id:8,name:"Beef Chapati",category:"Chapati",restaurant:"Urban Bites",price:10000,eta:17,emoji:"🌯"}];
const cats=[["All","🍽️"],["Pizza","🍕"],["Chapati","🌯"],["Chips","🍟"],["Burgers","🍔"],["Chicken","🍗"]],PAY="+256708802622";let activeOrderId=localStorage.munchActiveOrderId||"",orderTimer=null;let cat="All",cart=JSON.parse(localStorage.munchCart||"{}"),orders=JSON.parse(localStorage.munchOrders||"[]"),account=JSON.parse(localStorage.munchAccount||"null"),settings=JSON.parse(localStorage.munchSettings||'{"theme":"system","motion":true}'),loc=localStorage.munchLocation||"",historyPages=[];const API=localStorage.munchApiUrl||"http://localhost:3000";const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>"UGX "+n.toLocaleString("en-UG");
function save(){localStorage.munchCart=JSON.stringify(cart);localStorage.munchOrders=JSON.stringify(orders)}
function toast(t){let e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove("show"),2200)}
function renderCats(){$("#categories").innerHTML=cats.map(x=>`<button class="category ${x[0]==cat?"active":""}" data-cat="${x[0]}">${x[1]} ${x[0]}</button>`).join("");$$("[data-cat]").forEach(b=>b.onclick=()=>{cat=b.dataset.cat;renderCats();renderFoods()})}
function renderFoods(){let q=$("#searchInput").value.toLowerCase(),a=foods.filter(f=>(cat=="All"||f.category==cat)&&(`${f.name} ${f.restaurant}`.toLowerCase().includes(q)));$("#foodGrid").innerHTML=a.map(f=>`<article class="food-card"><button class="food-image" data-prod="${f.id}">${f.emoji}</button><div class="food-info"><h3 class="food-name">${f.name}</h3><div class="restaurant">${f.restaurant} · ${f.eta} min</div><div class="food-bottom"><div><div class="price">${money(f.price)}</div><div class="eta">Delivery estimate</div></div><button class="add-button" data-add="${f.id}">+</button></div></div></article>`).join("");$("#emptyState").classList.toggle("hidden",a.length>0);$$("[data-add]").forEach(b=>b.onclick=e=>{e.stopPropagation();add(+b.dataset.add)});$$("[data-prod]").forEach(b=>b.onclick=()=>product(+b.dataset.prod))}
function add(id){cart[id]=(cart[id]||0)+1;save();count();toast("Added to cart")}
function entries(){return Object.entries(cart).map(([id,q])=>({...foods.find(f=>f.id==+id),q}))}function sub(){return entries().reduce((s,f)=>s+f.price*f.q,0)}
function count(){$("#cartCount").textContent=Object.values(cart).reduce((a,b)=>a+b,0)}
function product(id){let f=foods.find(x=>x.id==id);$("#productDetails").innerHTML=`<div class="product-large"><div style="font-size:90px;text-align:center">${f.emoji}</div><p class="eyebrow">${f.category} · ${f.restaurant}</p><h2>${f.name}</h2><div class="price">${money(f.price)}</div><button class="primary-button" id="pa">Add to cart</button></div>`;openSheet("productSheet");$("#pa").onclick=()=>{add(id);closeSheets()}}
function openSheet(id){$("#sheetBackdrop").classList.add("show");$("#"+id).classList.add("show")}function closeSheets(){$$(".bottom-sheet").forEach(x=>x.classList.remove("show"));$("#sheetBackdrop").classList.remove("show")}
function openPage(id){historyPages.push(id);$("#"+id).classList.add("show")}function closePage(){let id=historyPages.pop();if(id)$("#"+id).classList.remove("show")}
function renderCheckout(){$("#checkoutItems").innerHTML=entries().map(f=>`<div class="checkout-row"><div class="mini-food">${f.emoji}</div><div><strong>${f.q} × ${f.name}</strong><p>${f.restaurant}</p></div><strong>${money(f.price*f.q)}</strong></div>`).join("");$("#subtotal").textContent=money(sub());$("#total").textContent=money(sub()+(entries().length?3000:0))}
function renderOrders(){$("#ordersList").innerHTML=orders.length?orders.map(o=>`<div class="order-card">🍽️ <div><strong>${o.items.length} item(s) · ${money(o.total)}</strong><p>${new Date(o.date).toLocaleString()}<br>${o.location}</p><small>${o.status}</small></div></div>`).join(""):`<div class="empty-state">📦<h3>No orders yet</h3><p>Your orders will appear here.</p></div>`}
function statusLabel(s){return ({new:"Order received",accepted:"Order accepted",preparing:"Being prepared",ready:"Ready for pickup",out_for_delivery:"Out for delivery",delivered:"Delivered",cancelled:"Cancelled"}[s]||s||"Order update")}
async function syncActiveOrder(){if(!activeOrderId||!account?.phone)return;try{let r=await fetch(`${API}/api/orders/${encodeURIComponent(activeOrderId)}?phone=${encodeURIComponent(account.phone)}`);if(!r.ok)return;let saved=await r.json();let i=orders.findIndex(o=>o.id===saved.id);if(i>=0)orders[i]=saved;else orders.unshift(saved);save();renderOrders();$("#activeOrder").classList.remove("hidden");$("#trackingTitle").textContent=statusLabel(saved.status);$("#trackingText").textContent=saved.status==="delivered"?"This order is complete.":`Status: ${statusLabel(saved.status)} · ETA ${saved.etaMinutes} minutes`;}catch(e){}}
function startOrderSync(){clearInterval(orderTimer);syncActiveOrder();orderTimer=setInterval(syncActiveOrder,5000)}
function renderAccount(){let ok=!!account;$("#accountButtonText").textContent=ok?account.name:"Create / sign in";$("#profileGreeting").textContent=ok?`Welcome, ${account.name}`:"Welcome to Munch";$("#profileAvatar").textContent=ok?account.name[0].toUpperCase():"M";$("#accountName").value=account?.name||"";$("#accountPhone").value=account?.phone||"";$("#accountEmail").value=account?.email||"";$("#accountPassword").value=account?.password||"";$("#logoutButton").classList.toggle("hidden",!ok)}
function settingsApply(){if(settings.theme=="dark")document.body.dataset.theme="dark";else document.body.removeAttribute("data-theme");document.body.classList.toggle("no-motion",!settings.motion);$("#themeValue").textContent=(settings.theme[0].toUpperCase()+settings.theme.slice(1))+" ›";$("#motionValue").textContent=settings.motion?"On ›":"Off ›";localStorage.munchSettings=JSON.stringify(settings)}
$("#locationButton").onclick=()=>openSheet("locationSheet");$("#sheetBackdrop").onclick=closeSheets;$$("[data-close-sheet]").forEach(b=>b.onclick=closeSheets);
$("#useLocation").onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>{$("#addressInput").value=`GPS location (${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)})`;toast("Current location detected")},()=>toast("Location permission denied")):toast("Location unavailable");
$("#saveLocation").onclick=()=>{loc=$("#addressInput").value.trim();if(!loc)return toast("Enter a delivery address");localStorage.munchLocation=loc;$("#locationText").textContent=loc;closeSheets();toast("Location saved")};
$("#searchInput").oninput=renderFoods;$("#clearSearch").onclick=()=>{$("#searchInput").value="";renderFoods()};$("#heroExplore").onclick=()=>$("#foodSection").scrollIntoView({behavior:"smooth"});$("#viewAll").onclick=()=>{cat="All";renderCats();$("#searchInput").value="";renderFoods()};
$("#paymentMethodsButton").onclick=()=>openSheet("paymentSheet");$("#copyPaymentNumber").onclick=async()=>{try{await navigator.clipboard.writeText(PAY)}catch(e){}toast("Payment number: +256 708 802 622")};
$("#placeOrder").onclick=async()=>{if(!entries().length)return toast("Your cart is empty");if(!loc)return toast("Choose delivery location first");if(!account)return toast("Create your account first");let es=entries(),o={date:new Date().toISOString(),createdAt:new Date().toISOString(),items:es,total:sub()+3000,location:loc,status:"new",etaMinutes:Math.max(...es.map(x=>x.eta)),paymentMethod:$("#paymentMethod").value,paymentStatus:"pending",customer:{name:account.name,phone:account.phone,email:account.email||""}};try{let r=await fetch(API+"/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(o)});if(!r.ok)throw new Error();let saved=await r.json();orders.unshift(saved);activeOrderId=saved.id;localStorage.munchActiveOrderId=saved.id;cart={};save();count();renderCheckout();renderOrders();closeSheets();$("#activeOrder").classList.remove("hidden");$("#trackingTitle").textContent=statusLabel(saved.status);$("#trackingText").textContent=`Status: ${statusLabel(saved.status)} · ETA ${saved.etaMinutes} minutes`;startOrderSync();toast("Order sent to Munch") }catch(e){toast("Could not reach Munch server")}};
$("#accountButton").onclick=()=>{renderAccount();openPage("accountPage")};$("#accountForm").onsubmit=e=>{e.preventDefault();account={name:$("#accountName").value.trim(),phone:$("#accountPhone").value.trim(),email:$("#accountEmail").value.trim(),password:$("#accountPassword").value};localStorage.munchAccount=JSON.stringify(account);renderAccount();toast("Account saved on this device")};$("#logoutButton").onclick=()=>{account=null;localStorage.removeItem("munchAccount");renderAccount();toast("Logged out")};
$("#settingsButton").onclick=()=>openPage("settingsPage");$("#themeToggle").onclick=()=>{settings.theme=settings.theme=="system"?"dark":settings.theme=="dark"?"light":"system";settingsApply();toast("Theme updated")};$("#motionToggle").onclick=()=>{settings.motion=!settings.motion;settingsApply()};$("#resetApp").onclick=()=>{if(confirm("Reset Munch data on this device?")){localStorage.clear();location.reload()}};
$("#savedAddressesButton").onclick=()=>openSheet("locationSheet");
$("#profileButton").onclick=()=>{renderAccount();openPage("profilePage")};
$("#trackButton").onclick=()=>toast("Live driver tracking will connect with the delivery backend");
$$(".nav-item").forEach(b=>b.onclick=()=>{let p=b.dataset.page;$$(".nav-item").forEach(x=>x.classList.toggle("active",x==b));if(p=="home"){historyPages=[];$$(".page-overlay").forEach(x=>x.classList.remove("show"));scrollTo(0,0)}else if(p=="orders"){renderOrders();openPage("ordersPage")}else if(p=="profile"){renderAccount();openPage("profilePage")}else{renderCartPage();openPage("cartPage")}});
function renderCartPage(){let e=entries();if(!$("#cartPage")){let s=document.createElement("section");s.id="cartPage";s.className="page-overlay";s.innerHTML='<div class="page-content"><div class="page-title"><button class="back-button" data-close-page>‹</button><div><p class="eyebrow">Ready when you are</p><h2>Your cart</h2></div></div><div id="cartPageItems"></div><button class="primary-button" id="cartCheckout">Checkout</button></div>';document.body.appendChild(s);$("#cartCheckout").onclick=()=>{renderCheckout();openSheet("checkoutSheet")};s.querySelector("[data-close-page]").onclick=closePage}$("#cartPageItems").innerHTML=e.length?e.map(f=>`<div class="order-card"><span style="font-size:30px">${f.emoji}</span><div style="flex:1"><strong>${f.name}</strong><p>${f.q} × ${money(f.price)}</p></div><button class="add-button" onclick="add(${f.id});renderCartPage()">+</button></div>`).join(""):'<div class="empty-state">🛒<h3>Your cart is empty</h3></div>'}
$$("[data-close-page]").forEach(b=>b.onclick=closePage);
addEventListener("popstate",()=>{if($$(".bottom-sheet.show").length)closeSheets();else closePage()});
addEventListener("keydown",e=>{if(e.key=="Escape"){if($$(".bottom-sheet.show").length)closeSheets();else closePage()}});
if(loc)$("#locationText").textContent=loc;settingsApply();renderCats();renderFoods();count();renderCheckout();renderOrders();renderAccount();renderCartPage();if(activeOrderId)startOrderSync();